version: "3.9"

services:
  db:
    image: postgres:14-bullseye
    hostname: postgres-db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build:
      context: .
    depends_on:
      - db
    environment:
      DB_HOST: postgres-db