name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the stack
        run: docker-compose -f docker-compose.ci.yml up -d

      -name: Run migrations
        run: poetry run python manage.py migrate

      - name: Stop containers
        if: always()
        run: docker-compose -f docker-compose.ci.yml down
