name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the stack
        run: docker-compose -f docker-compose.ci.yml up -d

      - name: Run migrations
        run: docker exec -i playarounds_web_1 poetry run python manage.py migrate

      - name: Stop containers
        if: always()
        run: docker-compose -f docker-compose.ci.yml down
